#01 Get RIKEN BRC mice having Mammalian Phenotype Ontology (MP) terms.
prefix obo: <http://purl.obolibrary.org/obo/>
prefix brcanimal:<http://metadb.riken.jp/db/rikenbrc_mouse/>
prefix obo: <http://purl.obolibrary.org/obo/>
SELECT DISTINCT ?mouse
WHERE {
    ?mouse rdfs:subClassOf brcanimal:Strain.
	?mouse obo:RO_0002200 ?mp.
}