# 01 Get RIKEN BRC mice having Mammalian Phenotype Ontology (MP) terms.
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX brcanimal:<http://metadb.riken.jp/db/rikenbrc_mouse/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT DISTINCT ?mouse
WHERE {
	?mouse rdfs:subClassOf brcanimal:Strain.
	?mouse obo:RO_0002200 ?mp.
}
